
--------BEGIN ERROR LOG ON: 11/30/2018 11:35:39 AM-------------------------------------------------
--------CONTROLLER/ACTION: General/HttpError404
--------MESSAGE: Path '/Views/Questions/EditorTemplates/AnswersForQuestion.cshtml' was not found.
--------STACK TRACE:    at System.Web.HttpNotFoundHandler.ProcessRequest(HttpContext context)
   at System.Web.HttpApplication.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 11:36:22 AM-------------------------------------------------
--------CONTROLLER/ACTION: Authentication/Authenticate
--------MESSAGE: The underlying provider failed on Open.
--------STACK TRACE:    at System.Data.Entity.Core.EntityClient.EntityConnection.Open()
   at System.Data.Entity.Core.Objects.ObjectContext.EnsureConnection(Boolean shouldMonitorTransactions)
   at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
   at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
   at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
   at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
   at System.Linq.Enumerable.SingleOrDefault[TSource](IEnumerable`1 source)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.<GetElementFunction>b__2[TResult](IEnumerable`1 sequence)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.ExecuteSingle[TResult](IEnumerable`1 query, Expression queryRoot)
   at System.Data.Entity.Core.Objects.ELinq.ObjectQueryProvider.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Data.Entity.Internal.Linq.DbQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
   at KTS_Testing_System.Controllers.AuthenticationController.Authenticate(LoginViewModel model, String returnUrl) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\AuthenticationController.cs:line 55
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 4:53:43 PM-------------------------------------------------
--------CONTROLLER/ACTION: Questions/Create:Request Submitted
--------MESSAGE: Object reference not set to an instance of an object.
--------STACK TRACE:    at KTS_Testing_System.Controllers.QuestionsController.Create(QuestionsVM questionsVM) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\QuestionsController.cs:line 294
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 4:54:07 PM-------------------------------------------------
--------CONTROLLER/ACTION: Questions/Create:Request Submitted
--------MESSAGE: validation
--------STACK TRACE:    at KTS_Testing_System.Controllers.QuestionsController.Create(QuestionsVM questionsVM) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\QuestionsController.cs:line 254
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 5:57:36 PM-------------------------------------------------
--------CONTROLLER/ACTION: Questions/Update:Submitted for question: adfasdfasdfasdfss
--------MESSAGE: An error occurred while updating the entries. See the inner exception for details.
--------STACK TRACE:    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at KTS_Testing_System.Controllers.QuestionsController.Update(QuestionsVM questionVM) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\QuestionsController.cs:line 562
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 5:57:58 PM-------------------------------------------------
--------CONTROLLER/ACTION: Questions/Update:Submitted for question: adfasdfasdfasdfss
--------MESSAGE: An error occurred while updating the entries. See the inner exception for details.
--------STACK TRACE:    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at KTS_Testing_System.Controllers.QuestionsController.Update(QuestionsVM questionVM) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\QuestionsController.cs:line 562
--------END OF ERROR LOG-------------------------------------------------------------------------

--------BEGIN ERROR LOG ON: 11/30/2018 5:59:58 PM-------------------------------------------------
--------CONTROLLER/ACTION: Questions/Update:Submitted for question: adfasdfasdfasdf
--------MESSAGE: An error occurred while updating the entries. See the inner exception for details.
--------STACK TRACE:    at System.Data.Entity.Internal.InternalContext.SaveChanges()
   at System.Data.Entity.Internal.LazyInternalContext.SaveChanges()
   at System.Data.Entity.DbContext.SaveChanges()
   at KTS_Testing_System.Controllers.QuestionsController.Update(QuestionsVM questionVM) in D:\Projects\KMC_Testing_System\KTS_Testing_System\KTS_Testing_System\Controllers\QuestionsController.cs:line 562
--------END OF ERROR LOG-------------------------------------------------------------------------
